jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: TimDaub/hetzner-cloud-deploy-server-action@v2
        with:
          server-name: "eliveltontech"
          server-image: "ubuntu-20.04"
          server-type: "cx31"
          ssh-key-name: "github"
          hcloud-token: ${{ secrets.HCLOUD_TOKEN }}