name: Github CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: mkdir -p ~/.ssh && ssh-keyscan -H 95.216.137.189 >> ~/.ssh/known_hosts
      - run: mkdir -p ~/.ssh/ && ssh-keyscan -H $95.216.137.189 >> ~/.ssh/known_hosts
      - run: ssh root@95.216.137.189 touch elivelton_was_here
      - run: ssh root@95.216.137.189 ls