name: Teste de Conexão SSH

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Teste de Conexão SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-o StrictHostKeyChecking=no"
          SOURCE: "."  # Você pode deixar como está ou especificar uma pasta se desejar
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
